CREATE TABLE "Aluno" (
	"idAluno" number NOT NULL UNIQUE,
	"nomeAluno" varchar2(255) NOT NULL,
	"cpfAluno" varchar2(255) NOT NULL,
	"dataNascimentoAluno" date NOT NULL,
	"anoInicioGraduacao" number NOT NULL,
	"mediaAluno" binary_float NOT NULL,
	"idCursoGraduacao" number,
	PRIMARY KEY ("idAluno")
);
CREATE TABLE "Curso" (
	"idGraduacao" number NOT NULL UNIQUE,
	"cursoGraduacao" varchar2(255) NOT NULL,
	"areaAtuacao" varchar2(255) NOT NULL,
	"tempoPeriodosTotal" number NOT NULL,
	PRIMARY KEY ("idGraduacao")
);
CREATE TABLE "Professor" (
	"idProfessor" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"nomeProfessor" varchar2(255) NOT NULL,
	"dataNascimentoProfessor" date NOT NULL,
	"dataContratacao" date NOT NULL,
	PRIMARY KEY ("idProfessor")
);
CREATE TABLE "Prova" (
	"idProva" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"dataAplicacaoProva" date NOT NULL,
	"idDisciplina" number NOT NULL,
	"qtdeQuestoes" number NOT NULL,
	"idProfessor" number,
	"tipoProva" varchar2(255) NOT NULL,
	"pesoProva" binary_float NOT NULL,
	PRIMARY KEY ("idProva")
);
-- Tabela de juncao para permitir que um Professor lecione varios Cursos (M:N).
CREATE TABLE "professorcurso" (
	"idProfessorCurso" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"idProfessor" number NOT NULL,
	"idGraduacao" number NOT NULL,
	"dataInicio" date,
	"dataFim" date,
	PRIMARY KEY ("idProfessorCurso")
);
CREATE TABLE "Disciplina" (
	"idDisciplina" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"nomeDisciplina" varchar2(255) NOT NULL,
	"cargaHoraria" binary_float NOT NULL,
	"periodoSugerido" number NOT NULL,
	"idCursoGraduacao" number NOT NULL,
	PRIMARY KEY ("idDisciplina")
);
CREATE TABLE "Turma" (
	"idTurma" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"idDisciplina" number NOT NULL,
	"idProfessor" number NOT NULL,
	"anoLetivo" number NOT NULL,
	"semestre" number NOT NULL,
	"turno" varchar2(255) NOT NULL,
	"sala" number NOT NULL,
	PRIMARY KEY ("idTurma")
);
ALTER TABLE "Aluno" ADD CONSTRAINT "Aluno_fk6" FOREIGN KEY ("idCursoGraduacao") REFERENCES "Curso"("idGraduacao");
ALTER TABLE "Prova" ADD CONSTRAINT "Prova_fk2" FOREIGN KEY ("idDisciplina") REFERENCES "Disciplina"("idDisciplina");
ALTER TABLE "Prova" ADD CONSTRAINT "Prova_fk4" FOREIGN KEY ("idProfessor") REFERENCES "Professor"("idProfessor");
ALTER TABLE "professorcurso" ADD CONSTRAINT "professorcurso_fk1" FOREIGN KEY ("idProfessor") REFERENCES "Professor"("idProfessor");
ALTER TABLE "professorcurso" ADD CONSTRAINT "professorcurso_fk2" FOREIGN KEY ("idGraduacao") REFERENCES "Curso"("idGraduacao");
ALTER TABLE "Disciplina" ADD CONSTRAINT "Disciplina_fk4" FOREIGN KEY ("idCursoGraduacao") REFERENCES "Curso"("idGraduacao");
ALTER TABLE "Turma" ADD CONSTRAINT "Turma_fk1" FOREIGN KEY ("idDisciplina") REFERENCES "Disciplina"("idDisciplina");
ALTER TABLE "Turma" ADD CONSTRAINT "Turma_fk2" FOREIGN KEY ("idProfessor") REFERENCES "Professor"("idProfessor");
CREATE INDEX "ix_professor_idCursoLecionado" ON "Professor" ("idCursoLecionado");
CREATE UNIQUE INDEX "ux_professorcurso" ON "professorcurso" ("idProfessor", "idGraduacao");
COMMENT ON COLUMN "Aluno"."idCursoGraduacao" IS 'FK para o curso de graduacao do aluno (Curso 1:N Aluno).';
COMMENT ON COLUMN "Prova"."idProfessor" IS 'FK: professor responsavel pela prova (aplicacao/criacao).';
COMMENT ON TABLE "professorcurso" IS 'Tabela de juncao para permitir que um Professor lecione varios Cursos (M:N).';
COMMENT ON COLUMN "professorcurso"."idProfessorCurso" IS 'Identificador da associacao Professor_Curso.';
COMMENT ON COLUMN "professorcurso"."idProfessor" IS 'FK para Professor.';
COMMENT ON COLUMN "professorcurso"."idGraduacao" IS 'FK para Curso.';
COMMENT ON COLUMN "professorcurso"."dataInicio" IS 'Opcional: inicio do vinculo.';
COMMENT ON COLUMN "professorcurso"."dataFim" IS 'Opcional: fim do vinculo.';
